### ISSUE TITLE
How about the sparsity implementation

### ISSUE THREAD

**Issue by minghaoBD** [Jangho-Kim/PSG-pytorch#1]
Hi, thanks for the great work!

I notice there are only the quantization-related models and codes in your repo. But I am also very interested in your sparsity functionality. So could you please share the parts or the methods to implement it efficiently? 

Thank you!

**Comment by Jangho-Kim** [comment]
Hello!
Thank you for the attention.
For pruning case, you can just change the target value as zero
Ex) scale = torch.abs(x-x_restore)  -> scale = torch.abs(x) # x_restore = 0

Thank you.

**Comment by minghaoBD** [comment]
I got it, thank you. To followup, after changing this piece of code, do I need to train from scratch using this pruning target value. The same logic, if I want to get the quantization results which are different from your provided w4 version, I still need to train the model with my own w_bit in train.py. And the w_bit should be the same with the one in eval.py. Is my understanding right?

**Comment by Jangho-Kim** [comment]
Yes. PSGD needs a target value (bits or zero). However, you can check the results with different bit widths using the model trained with a specific target bit  in Table 2 of the original paper.

**Comment by minghaoBD** [comment]
Great! Appreciate your response.
